name: Deploy ATC monitoring @ Dev1
on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Run the tests."
        type: boolean
        required: true
    branches:
      - '**'
jobs:
  tests:
    runs-on: ubuntu-latest
    if: ${{ inputs.run_tests }} 
    steps:
      - name: Run unit tests
        run: echo Testing the branch...
      - name: Fail
        run: exit 1

  deploy:
    needs: tests
    if: always() && needs.tests.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Build & Deploy
        run: echo Building and deploying...